"""
PDF Report Generator.
Phase 4.2.3: WeasyPrint-based PDF generation.
"""
from pathlib import Path
from typing import Optional
from jinja2 import Template
from src.vendors.reporting_handoff.reporting.models import ReportData


# Default HTML template
DEFAULT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ data.study_title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
        }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        table { 
            border-collapse: collapse; 
            width: 100%; 
            margin: 20px 0;
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 12px; 
            text-align: left; 
        }
        th { background-color: #3498db; color: white; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .summary-box {
            background: #ecf0f1;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .significant { color: #27ae60; font-weight: bold; }
        .not-significant { color: #e74c3c; }
        .plot-container { text-align: center; margin: 30px 0; }
        .plot-container img { max-width: 100%; height: auto; }
        footer { 
            margin-top: 50px; 
            padding-top: 20px; 
            border-top: 1px solid #ddd; 
            font-size: 0.9em; 
            color: #7f8c8d; 
        }
    </style>
</head>
<body>
    <h1>{{ data.study_title }}</h1>
    <p><em>Generated: {{ data.generated_at.strftime('%Y-%m-%d %H:%M') }}</em></p>
    
    <div class="summary-box">
        <h2>Executive Summary</h2>
        <p><strong>Target Cohort:</strong> {{ data.target_name }} (n={{ data.target_cohort_size }})</p>
        <p><strong>Comparator Cohort:</strong> {{ data.comparator_name }} (n={{ data.comparator_cohort_size }})</p>
        {% if data.hazard_ratio %}
        <p><strong>Hazard Ratio:</strong> {{ "%.2f"|format(data.hazard_ratio.hr) }} 
           (95% CI: {{ "%.2f"|format(data.hazard_ratio.ci_lower) }}-{{ "%.2f"|format(data.hazard_ratio.ci_upper) }})</p>
        <p><strong>p-value:</strong> {{ "%.4f"|format(data.hazard_ratio.p_value) }}
           {% if data.hazard_ratio.p_value < 0.05 %}
           <span class="significant">(Statistically Significant)</span>
           {% else %}
           <span class="not-significant">(Not Significant)</span>
           {% endif %}
        </p>
        {% endif %}
    </div>
    
    <h2>Study Design</h2>
    <p><strong>Analysis Method:</strong> {{ data.analysis_method }}</p>
    <p><strong>Outcome:</strong> {{ data.outcome_name }}</p>
    
    {% if data.km_plot_path %}
    <div class="plot-container">
        <h2>Kaplan-Meier Survival Curves</h2>
        <img src="{{ data.km_plot_path }}" alt="Kaplan-Meier Curves">
    </div>
    {% endif %}
    
    {% if data.forest_plot_path %}
    <div class="plot-container">
        <h2>Forest Plot</h2>
        <img src="{{ data.forest_plot_path }}" alt="Forest Plot">
    </div>
    {% endif %}
    
    <footer>
        <p>Report generated by TELOS 3.1 - Target Trial Emulation System</p>
    </footer>
</body>
</html>
"""


class PDFGenerator:
    """Generate PDF reports from ReportData."""
    
    def __init__(self, template_path: Optional[str] = None):
        """
        Args:
            template_path: Path to custom HTML template. Uses default if None.
        """
        if template_path and Path(template_path).exists():
            with open(template_path) as f:
                self.template = Template(f.read())
        else:
            self.template = Template(DEFAULT_TEMPLATE)
    
    def render_html(self, report_data: ReportData) -> str:
        """Render HTML from report data."""
        return self.template.render(data=report_data)
    
    def generate(self, report_data: ReportData, output_path: str):
        """
        Generate PDF from report data.
        
        Args:
            report_data: ReportData instance
            output_path: Path to save PDF
        """
        from weasyprint import HTML
        
        html_content = self.render_html(report_data)
        HTML(string=html_content).write_pdf(output_path)
    
    def generate_html_only(self, report_data: ReportData, output_path: str):
        """Save as HTML instead of PDF (for debugging)."""
        html_content = self.render_html(report_data)
        with open(output_path, 'w') as f:
            f.write(html_content)
