"""
Cohort Generation via ATLAS WebAPI.

Registers TROY and ARTEMIS Circe JSON as cohort definitions,
generates SQL, executes cohort generation on SYNTHEA CDM,
and reports patient counts.

Usage:
    conda run -n artemis python scripts/cohort_via_webapi.py
"""
import json
import os
import sys
import time
import argparse
import requests
import psycopg2

# ============================================================
# Configuration
# ============================================================
WEBAPI_URL = os.environ.get("WEBAPI_URL", "http://127.0.0.1/WebAPI")
SOURCE_KEY = os.environ.get("SOURCE_KEY", "SYNTHEA23M")

TROY_PATH = "data/sample/LEADER/[TROY] Liraglutide (LEADER) v3.4.json"
ARTEMIS_PATH = "data/sample/LEADER/ARTEMIS_LEADER_design_paper_e2e.json"

DB_HOST = os.environ.get("OMOP_DB_HOST", "localhost")
DB_PORT = os.environ.get("OMOP_DB_PORT", "5432")
DB_NAME = os.environ.get("OMOP_DB_NAME", "ohdsi")
DB_USER = os.environ.get("OMOP_DB_USER", "postgres")
DB_PASS = os.environ.get("OMOP_DB_PASS", "mypass")
RESULTS_SCHEMA = os.environ.get("CDM_SCHEMA", "synthea23m") + "_results"

POLL_INTERVAL = 5  # seconds
MAX_POLL_TIME = 600  # 10 minutes


# ============================================================
# WebAPI Client
# ============================================================
class WebAPIClient:
    """Simple ATLAS WebAPI client for cohort operations."""

    def __init__(self, base_url: str):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({"Content-Type": "application/json"})

    def check_health(self) -> dict:
        """Check WebAPI availability."""
        resp = self.session.get(f"{self.base_url}/info")
        resp.raise_for_status()
        return resp.json()

    def list_cohort_definitions(self) -> list:
        """List all existing cohort definitions."""
        resp = self.session.get(f"{self.base_url}/cohortdefinition")
        resp.raise_for_status()
        return resp.json()

    def create_cohort_definition(self, name: str, circe_json: dict) -> dict:
        """Register a new cohort definition (reuse if name already exists)."""
        # Check for existing definition with same name
        existing = self.list_cohort_definitions()
        for d in existing:
            if d["name"] == name:
                full = self.get_cohort_definition(d["id"])
                return full

        payload = {
            "name": name,
            "description": "Auto-generated by cohort_via_webapi.py",
            "expressionType": "SIMPLE_EXPRESSION",
            "expression": circe_json,  # WebAPI expects JSON object, not string
        }
        resp = self.session.post(
            f"{self.base_url}/cohortdefinition", json=payload
        )
        resp.raise_for_status()
        return resp.json()

    def get_cohort_definition(self, cohort_id: int) -> dict:
        """Get cohort definition details."""
        resp = self.session.get(f"{self.base_url}/cohortdefinition/{cohort_id}")
        resp.raise_for_status()
        return resp.json()

    def generate_sql(self, circe_json: dict) -> str:
        """Generate SQL from Circe JSON (for inspection only)."""
        payload = {
            "expression": circe_json,
            "options": {"generateStats": True},
            "targetDialect": "postgresql",
        }
        resp = self.session.post(
            f"{self.base_url}/cohortdefinition/sql", json=payload
        )
        resp.raise_for_status()
        return resp.json().get("templateSql", "")

    def start_generation(self, cohort_id: int, source_key: str) -> dict:
        """Start cohort generation on a specific source."""
        resp = self.session.get(
            f"{self.base_url}/cohortdefinition/{cohort_id}/generate/{source_key}"
        )
        resp.raise_for_status()
        return resp.json()

    def get_generation_info(self, cohort_id: int) -> list:
        """Get generation status for a cohort definition."""
        resp = self.session.get(
            f"{self.base_url}/cohortdefinition/{cohort_id}/info"
        )
        resp.raise_for_status()
        return resp.json()

    def delete_cohort_definition(self, cohort_id: int):
        """Delete a cohort definition."""
        resp = self.session.delete(
            f"{self.base_url}/cohortdefinition/{cohort_id}"
        )
        resp.raise_for_status()


# ============================================================
# Cohort Generation Flow
# ============================================================
def load_circe_json(path: str) -> dict:
    """Load Circe JSON, handling both raw expression and ATLAS export formats."""
    with open(path) as f:
        data = json.load(f)

    # If it's an ATLAS export (has "expression" as string), parse it
    if "expression" in data and isinstance(data["expression"], str):
        return json.loads(data["expression"])

    # If it already has PrimaryCriteria, it's a raw Circe expression
    if "PrimaryCriteria" in data:
        return data

    raise ValueError(f"Cannot parse Circe JSON from {path}: "
                     f"keys = {list(data.keys())}")


def wait_for_generation(client: WebAPIClient, cohort_id: int,
                        source_key: str) -> dict:
    """Poll generation status until complete or timeout."""
    start = time.time()
    while time.time() - start < MAX_POLL_TIME:
        info_list = client.get_generation_info(cohort_id)
        for info in info_list:
            status = info.get("status", "")

            if status == "COMPLETE":
                return info
            elif status == "FAILED":
                print(f"  ❌ Generation FAILED!")
                if info.get("failMessage"):
                    print(f"     {info['failMessage']}")
                return info
            else:
                elapsed = int(time.time() - start)
                print(f"  ⏳ Status: {status} ({elapsed}s elapsed)",
                      end="\r")

        time.sleep(POLL_INTERVAL)

    print(f"\n  ⚠ Timeout after {MAX_POLL_TIME}s")
    return {}


def query_cohort_count(cohort_id: int) -> int:
    """Query the results table for patient count."""
    conn = psycopg2.connect(
        host=DB_HOST, port=DB_PORT, dbname=DB_NAME,
        user=DB_USER, password=DB_PASS
    )
    try:
        cur = conn.cursor()
        cur.execute(f"""
            SELECT COUNT(DISTINCT subject_id)
            FROM {RESULTS_SCHEMA}.cohort
            WHERE cohort_definition_id = %s
        """, (cohort_id,))
        count = cur.fetchone()[0]
        cur.close()
        return count
    finally:
        conn.close()


def run_cohort(client: WebAPIClient, name: str, circe_json: dict,
               source_key: str) -> dict:
    """Full flow: register → generate SQL → execute → count patients."""
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")

    # Stats
    n_cs = len(circe_json.get("ConceptSets", []))
    n_rules = len(circe_json.get("InclusionRules", []))
    print(f"  ConceptSets: {n_cs}, InclusionRules: {n_rules}")

    # 1. Register cohort definition
    print(f"\n  📝 Step 1: Registering cohort definition...")
    result = client.create_cohort_definition(name, circe_json)
    cohort_id = result["id"]
    print(f"  ✅ Registered as ID={cohort_id}")

    # 2. Generate SQL (for inspection)
    print(f"\n  🔧 Step 2: Generating SQL...")
    template_sql = client.generate_sql(circe_json)
    sql_lines = template_sql.count("\n")
    sql_bytes = len(template_sql.encode())
    print(f"  ✅ SQL generated: {sql_lines} lines, {sql_bytes:,} bytes")

    # Save SQL to file
    sql_dir = os.path.dirname(ARTEMIS_PATH)
    sql_filename = name.replace(" ", "_").replace("(", "").replace(")", "")
    sql_path = os.path.join(sql_dir, f"{sql_filename}_generated.sql")
    with open(sql_path, "w") as f:
        f.write(template_sql)
    print(f"  💾 SQL saved: {sql_path}")

    # 3. Check if already generated
    existing_info = client.get_generation_info(cohort_id)
    already_complete = False
    for info in existing_info:
        if info.get("status") == "COMPLETE":
            already_complete = True
            person_count = info.get("personCount")
            duration = info.get("executionDuration")
            print(f"\n  ✅ Already generated! (personCount={person_count}, "
                  f"duration={duration}ms)")
            break

    if not already_complete:
        # Start cohort generation
        print(f"\n  🚀 Step 3: Starting cohort generation on {source_key}...")
        client.start_generation(cohort_id, source_key)

        # Wait for completion
        print(f"  ⏳ Step 4: Waiting for generation...")
        gen_info = wait_for_generation(client, cohort_id, source_key)
        print()  # clear \r line

        status = gen_info.get("status", "UNKNOWN") if gen_info else "UNKNOWN"
        if status != "COMPLETE":
            print(f"  ❌ Generation did not complete (status: {status})")
            return {"id": cohort_id, "status": status, "count": 0}

        print(f"  ✅ Generation COMPLETE")

    # Query patient count
    print(f"\n  📊 Querying patient count...")
    count = query_cohort_count(cohort_id)
    print(f"  ✅ Patients in cohort: {count:,}")

    return {"id": cohort_id, "status": "COMPLETE", "count": count,
            "sql_path": sql_path}


# ============================================================
# Main
# ============================================================
def main():
    parser = argparse.ArgumentParser(
        description="Generate cohorts via ATLAS WebAPI"
    )
    parser.add_argument("--troy", default=TROY_PATH,
                        help="Path to TROY reference JSON")
    parser.add_argument("--artemis", default=ARTEMIS_PATH,
                        help="Path to ARTEMIS output JSON")
    parser.add_argument("--source", default=SOURCE_KEY,
                        help="WebAPI source key (default: SYNTHEA23M)")
    parser.add_argument("--skip-troy", action="store_true",
                        help="Skip TROY cohort generation")
    parser.add_argument("--skip-artemis", action="store_true",
                        help="Skip ARTEMIS cohort generation")
    parser.add_argument("--cleanup", action="store_true",
                        help="Delete created cohort definitions after run")
    args = parser.parse_args()

    # Health check
    client = WebAPIClient(WEBAPI_URL)
    print("🏥 Checking WebAPI health...")
    try:
        info = client.check_health()
        print(f"  ✅ WebAPI {info['version']} is online")
    except Exception as e:
        print(f"  ❌ WebAPI not reachable: {e}")
        sys.exit(1)

    # List existing cohorts
    existing = client.list_cohort_definitions()
    print(f"  📋 Existing cohort definitions: {len(existing)}")
    for d in existing:
        print(f"     - [{d['id']}] {d['name']}")

    results = {}

    # --- TROY ---
    if not args.skip_troy:
        troy_json = load_circe_json(args.troy)
        results["troy"] = run_cohort(
            client, "TROY LEADER (Liraglutide)", troy_json, args.source
        )

    # --- ARTEMIS ---
    if not args.skip_artemis:
        artemis_json = load_circe_json(args.artemis)
        results["artemis"] = run_cohort(
            client, "ARTEMIS LEADER (Auto-generated)", artemis_json, args.source
        )

    # --- Comparison ---
    print(f"\n{'='*60}")
    print(f"  COMPARISON SUMMARY")
    print(f"{'='*60}")

    if "troy" in results and "artemis" in results:
        troy_n = results["troy"]["count"]
        artemis_n = results["artemis"]["count"]
        overlap_pct = (min(troy_n, artemis_n) / max(troy_n, artemis_n) * 100
                       if max(troy_n, artemis_n) > 0 else 0)

        print(f"  TROY  patients: {troy_n:>8,}")
        print(f"  ARTEMIS patients: {artemis_n:>8,}")
        print(f"  Size ratio:     {overlap_pct:>7.1f}%")

        if troy_n > 0:
            diff = artemis_n - troy_n
            pct = diff / troy_n * 100
            direction = "more" if diff > 0 else "fewer"
            print(f"  ARTEMIS has {abs(diff):,} {direction} patients "
                  f"({pct:+.1f}%)")
    else:
        for label, r in results.items():
            print(f"  {label.upper()}: {r['count']:,} patients "
                  f"(status: {r['status']})")

    # Cleanup
    if args.cleanup:
        print(f"\n🧹 Cleaning up cohort definitions...")
        for label, r in results.items():
            try:
                client.delete_cohort_definition(r["id"])
                print(f"  ✅ Deleted [{r['id']}] {label}")
            except Exception as e:
                print(f"  ⚠ Could not delete [{r['id']}]: {e}")

    print(f"\n✅ Done!")


if __name__ == "__main__":
    main()
