#!/usr/bin/env python3
"""Refuse a delivery whose concept-set members Atlas cannot render.

WebAPI does not need this. CIRCE compiles a concept set from CONCEPT_ID alone, so
a member missing every other field still translates to correct SQL -- measured on
the 2026-09-12 delivery, which WebAPI turned into SQL for all six files while
Atlas could not draw it.

Atlas is the part that breaks. It renders a concept set as a DataTable whose
columns read `concept.<FIELD>`; a member without one of those keys aborts the
whole table with

    DataTables warning: table id=... - Requested unknown parameter
    'concept.DOMAIN_ID' for row 13, column 2

and the cohort is never generated by the person sitting in front of it. That is
what happened at Dong-A on the 2026-09-12 delivery: its CAROLINA cells came back
blank rather than zero.

The required set below is what Atlas actually reads, taken from the source rather
than from memory:

  ConceptSetViewer.js         CONCEPT_ID, CONCEPT_NAME, DOMAIN_ID, VOCABULARY_ID
  conceptset-editor.js        CONCEPT_ID, DOMAIN_ID, CONCEPT_CODE,
                              STANDARD_CONCEPT, STANDARD_CONCEPT_CAPTION

Fields Atlas reads only on search results (RELATIONSHIPS, RECORD_COUNT,
PERSON_COUNT, DESCENDANT_RECORD_COUNT) are NOT required -- healthy members in
every delivered file lack them too.

Read-only. Never writes or fixes anything.

Usage:
    python3 scripts/verify_atlas_renderable.py <dir-or-file> [...]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# What Atlas dereferences as concept.<FIELD> when drawing a concept set.
REQUIRED = (
    "CONCEPT_ID",
    "CONCEPT_NAME",
    "DOMAIN_ID",
    "VOCABULARY_ID",
    "CONCEPT_CODE",
    "STANDARD_CONCEPT",
    "STANDARD_CONCEPT_CAPTION",
)


def check_file(path: Path) -> list[str]:
    doc = json.loads(path.read_text())
    problems: list[str] = []
    for cs in doc.get("ConceptSets") or []:
        items = ((cs.get("expression") or {}).get("items")) or []
        for row, item in enumerate(items):
            concept = item.get("concept") or {}
            missing = [f for f in REQUIRED if f not in concept]
            if missing:
                problems.append(
                    f"codeset {cs.get('id')} {cs.get('name')!r} row {row} "
                    f"(CONCEPT_ID {concept.get('CONCEPT_ID')}, "
                    f"isExcluded={item.get('isExcluded')}): missing {missing}"
                )
    return problems


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2

    files: list[Path] = []
    for arg in argv:
        p = Path(arg)
        files.extend(sorted(p.glob("*.circe.json")) if p.is_dir() else [p])
    if not files:
        print("no *.circe.json found")
        return 2

    bad = 0
    for f in files:
        problems = check_file(f)
        if problems:
            bad += 1
            print(f"FAIL  {f.name}  ({len(problems)} member(s) Atlas cannot render)")
            for line in problems[:10]:
                print(f"        {line}")
            if len(problems) > 10:
                print(f"        ... {len(problems) - 10} more")
        else:
            print(f"PASS  {f.name}")

    print(f"\n{len(files) - bad}/{len(files)} files renderable by Atlas")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
